# Comment out refences to provider URLs, API keys, and models you are not using

# ============= LLM FACTORY ===========================
API_KEY="YOUR_KEY_HERE"
API_URL="https://data.ai.uky.edu/llm-factory/openai/v1"
MODEL="MODEL_NAME_HERE"
# =====================================================


# ============= OpenRouter settings ===================
#API_KEY="YOUR_KEY_HERE"
#API_URL="https://openrouter.ai/api/v1"
#MODEL="MODEL_NAME_HERE"
# =====================================================


# ============= local ollama settings =================
#API_KEY="ollama"
#API_URL="http://localhost:11434/v1"
#MODEL="MODEL_NAME_HERE"
# =====================================================
