name: RAG-presentation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - toml
  - typing
  - pip
  - pip:
    - openai>=1.3.0
    - typing-extensions


# conda env create -f environment.yml
# conda env update -f environment.yml
# conda activate RAG-presentation
# conda deactivate